### ISSUE TITLE
event.blockingList  unreachable

### ISSUE THREAD

**Issue by Valodya89** [MySocialApp/mysocialapp-swift-client#14]
I can't get event list,the request got me "Server error. 500"

Please see attached screenshot

![screen shot 2018-06-26 at 7 35 16 pm](https://user-images.githubusercontent.com/9318170/41923309-29f6bcf6-7978-11e8-860a-58d03227ed4f.png)

* Swift version: 4.2
* xCode version: 9.4.1

**Comment by Gobountz** [comment]
Hi @Valodya89, this pagination problem is just fixed in the 1.0.18 version.

Best regards.

**Comment by davittorosyan** [comment]
@Gobountz problem still not solved.

when we set **page 0, size 20**, this is works good, but when in next cycle  we set **page 20, size 20** this return 0 items, but we have over 100 events.

Swift version: 4.2
MSA SDK version: 1.0.19
xCode version: 9.4.1

**Comment by Gobountz** [comment]
@davittorosyan the pagination system is based on pages, not on offset. So one page = {size} elements.
In your case, if you want to iterate over all the events, you will need to call :
- page 0, size 20 => the 20 first events
- page 1, size 20 => the 20 events in the second page, so events from 21 to 40
- page 2, size 20 => the 20 events in the third page, so events from 41 to 60
- ...

**Comment by davittorosyan** [comment]
@Gobountz Thank you, it works.
Another question, how can we set event start date? This is exist in Java sdk.
I dont want to show past events, so how can i set start date from today for example?
Its not good to get all events then filter, will be good get already filtered events.

In Java we have 
"getEvents(date,size)" function where i can send date
But in swift only "page" and "size"

**Comment by davittorosyan** [comment]
@Gobountz thanks for adding feature.
For first call this is working fine, for page 0, but when pagination in action, page 1, 2 etc... we again get past events.
Can you please check this?

thaks
